"""
immune.py — Epistemic Immune System
by William Ashioya | SHOAL | github.com/Ashioya-ui/ChiralCheck

WHAT THIS IS:
  A runtime action gate for AI agents. Before any proposed action executes,
  it is routed to the appropriate epistemic detector based on risk level.
  If hallucination/incoherence is detected above threshold, the action is
  blocked, access is conditionally revoked, and state is rolled back.

THREE DETECTORS (grounded in published research):

  LOW risk  → Semantic Entropy  (Farquhar et al., Nature 2024)
    Sample K responses to the same prompt at non-zero temperature.
    Cluster by cosine similarity using Voyage embeddings.
    Compute Shannon entropy over the cluster distribution.
    High entropy = agent is semantically uncertain = likely confabulating.
    Black-box compatible: no token probabilities required.

  HIGH risk → Covariance Log-Det  (Chen et al., ICLR 2024 — INSIDE proxy)
    Generate K adversarial perturbations of the proposed action.
    Embed all of them and measure the log-det of the covariance matrix.
    Diffuse cloud = action plan has no stable semantic core = block it.
    NOTE: True EigenScore requires white-box hidden state access.
    This is the black-box proxy from ChiralCheck T2 — same principle,
    external embeddings instead of internal activations.

  REASONING risk → Effective Complexity proxy  (Gell-Mann & Lloyd, 2010)
    Pass the reasoning trace through score_utility() from axes.py.
    High isolation_index = claims float unsupported = incoherent reasoning.
    Not a Kolmogorov complexity calculation — a structural proxy.

INTEGRATION:
  Connects directly to providers.py, chiral.py, and axes.py.
  No standalone mocks. All detectors use real LLM + embedding calls.

RED TEAM FIXES vs the original prototype:
  - semantic entropy: string-length mock replaced with real embedding clusters
  - eigenscore: white-box stub replaced with covariance log-det (black-box)
  - effective_complexity: "synergy" heuristic replaced with utility isolation index
  - sampled_responses: generated by LLM at temperature, not passed pre-made
  - thresholds: documented with calibration notes, not raw guesses
  - rollback: honest about scope (in-memory only)
  - full integration with providers.py / axes.py / chiral.py
"""

from __future__ import annotations
import logging
import math
import time
import json
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable

from providers import LLMProvider, EmbedProvider, ProviderError

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | CHIRAL-IMMUNE | %(message)s",
)
logger = logging.getLogger(__name__)


# ── Data structures ─────────────────────────────────────────────────────────

class TaskRisk(Enum):
    LOW       = "low"        # Text generation, summarisation, drafting
    HIGH      = "high"       # Shell execution, file ops, API calls, deletions
    REASONING = "reasoning"  # Complex chain-of-thought, data analysis, planning


@dataclass
class AgentAction:
    agent_id:         str
    proposed_command: str
    task_risk:        TaskRisk
    context:          str = ""       # Optional: the goal/instruction that triggered this action


@dataclass
class ImmuneVerdict:
    passed:             bool
    score:              float
    threshold:          float
    detector_used:      str
    agent_id:           str
    proposed_command:   str
    task_risk:          TaskRisk
    detail:             str = ""
    elapsed_s:          float = 0.0


# ── Detectors ────────────────────────────────────────────────────────────────

class EpistemicDetectors:
    """
    Three detectors, each grounded in published research.
    All use the ChiralCheck provider stack — no standalone mocks.
    """

    # ── 1. Semantic Entropy (LOW risk) ─────────────────────────────────────

    @staticmethod
    def semantic_entropy(
        prompt:   str,
        llm:      LLMProvider,
        embed:    EmbedProvider,
        k:        int = 5,
        thr:      float = 0.82,
    ) -> tuple[float, str]:
        """
        Farquhar et al., Nature 2024.

        Steps:
          1. Sample K responses at non-zero temperature (0.8)
          2. Embed all K + original with Voyage/provider
          3. Cluster by cosine similarity (greedy, threshold=thr)
          4. Compute Shannon entropy over cluster size distribution

        Returns (entropy_score 0-1, detail_string).
        Higher score = more semantic uncertainty = more likely confabulating.

        Black-box compatible: requires only text outputs and an embedding model.
        """
        _SYS = "Answer the following directly and concisely."

        # Step 1: sample K responses at high temperature
        responses: list[str] = []
        def _sample(_):
            try:
                return llm.complete(_SYS, prompt, max_tokens=256, temperature=0.8)
            except ProviderError:
                return None

        with ThreadPoolExecutor(max_workers=min(k, 6)) as ex:
            for r in as_completed([ex.submit(_sample, i) for i in range(k)]):
                try:
                    v = r.result()
                    if v: responses.append(v)
                except Exception:
                    pass

        if len(responses) < 2:
            return 0.5, "Insufficient samples — defaulting to uncertain"

        # Step 2: embed all responses
        try:
            vecs = embed.embed(responses, input_type="document")
        except ProviderError as e:
            return 0.5, f"Embedding failed: {e}"

        if not vecs or len(vecs) < 2:
            return 0.5, "Embedding returned too few vectors"

        # Steps 3+4: cluster + entropy (reuse ChiralCheck's _entropy logic)
        entropy = _cosine_cluster_entropy(vecs, thr=thr)
        # Normalise: max entropy for k clusters = log(k)
        max_entropy = math.log(len(vecs)) if len(vecs) > 1 else 1.0
        normalised  = entropy / max_entropy if max_entropy > 0 else 0.0
        clusters    = _count_clusters(vecs, thr=thr)

        detail = (
            f"Sampled {len(responses)} responses → {clusters} semantic clusters. "
            f"Entropy: {round(entropy, 3)} nats (normalised: {round(normalised, 3)})"
        )
        return round(normalised, 4), detail

    # ── 2. Covariance Log-Det (HIGH risk) ───────────────────────────────────

    @staticmethod
    def covariance_log_det(
        action:   str,
        llm:      LLMProvider,
        embed:    EmbedProvider,
        k:        int = 6,
    ) -> tuple[float, str]:
        """
        Black-box proxy for EigenScore (Chen et al., ICLR 2024 — INSIDE).

        True EigenScore requires white-box access to internal LLM activations
        (penultimate hidden states). This proxy uses the same geometric intuition
        with external embeddings of adversarially-varied action descriptions.

        Steps:
          1. Generate K adversarial re-framings of the proposed action
          2. Embed all K + original
          3. Compute log-det of diagonal covariance (normalised by dim)
          4. Map to 0-1 danger score: near-zero log-det = tight cloud = stable

        NOTE: Very negative log-det = tight cloud = action is well-defined = SAFE.
              Near-zero or positive = diffuse cloud = action is ambiguous/unstable = DANGEROUS.
        Returns (danger_score 0-1, detail_string).
        """
        angles = [
            ("adversarial misinterpretation", 0.9),
            ("minimal paraphrase",             0.3),
            ("worst-case interpretation",      1.0),
            ("scope expansion",                0.8),
            ("scope reduction",                0.6),
            ("equivalent but different syntax",0.5),
        ]
        _SYS = "Output only the rewritten text. No preamble."

        variants: list[str] = [action]

        def _vary(angle: str, temp: float) -> str | None:
            try:
                return llm.complete(
                    _SYS,
                    f"Rewrite this action from the perspective of a {angle}. "
                    f"Preserve the core intent but change framing and syntax. "
                    f"ONLY the rewrite.\n\nAction: {action}",
                    max_tokens=200, temperature=temp,
                )
            except ProviderError:
                return None

        with ThreadPoolExecutor(max_workers=min(k, 6)) as ex:
            fmap = {ex.submit(_vary, a, t): (a, t) for a, t in angles[:k]}
            for f in as_completed(fmap):
                try:
                    r = f.result()
                    if r and r.strip() != action.strip():
                        variants.append(r)
                except Exception:
                    pass

        if len(variants) < 3:
            return 0.8, "Insufficient variants — defaulting to high danger"

        try:
            vecs = embed.embed(variants, input_type="document")
        except ProviderError as e:
            return 0.8, f"Embedding failed: {e}"

        if not vecs or len(vecs) < 3:
            return 0.8, "Embedding returned too few vectors"

        # Clip top 10% dimensions (prevent extreme dims masking spread)
        clipped  = _clip_features(vecs)
        nd       = _log_det_normalised(clipped)

        # Map log-det to danger score:
        # nd < -6.5 → very tight cloud → safe (0.1)
        # nd near 0 → diffuse cloud → dangerous (0.9)
        if nd < -6.5:   danger = 0.10
        elif nd < -5.5: danger = round(0.10 + (nd + 6.5) / 1.0 * 0.20, 3)
        elif nd < -4.5: danger = round(0.30 + (nd + 5.5) / 1.0 * 0.30, 3)
        else:           danger = min(0.95, round(0.60 + (nd + 4.5) * 0.05, 3))

        detail = (
            f"Generated {len(variants)-1} action variants. "
            f"Log-det (normalised): {round(nd, 4)}. "
            f"Danger score: {danger}"
        )
        return danger, detail

    # ── 3. Effective Complexity proxy (REASONING risk) ──────────────────────

    @staticmethod
    def effective_complexity_proxy(
        reasoning_trace: str,
        llm:             LLMProvider,
    ) -> tuple[float, str]:
        """
        Structural proxy for Gell-Mann & Lloyd's Effective Complexity.

        Uses score_utility() from axes.py — the isolation_index measures
        what fraction of claims in the reasoning trace float free with
        no mutual support from other claims.

        High isolation = high AIC / low regularity = incoherent reasoning.
        Low isolation  = dense, self-reinforcing structure = coherent.

        Returns (incoherence_score 0-1, detail_string).
        NOTE: This is a structural proxy, not a Kolmogorov complexity calculation.
        """
        from axes import score_utility

        result = score_utility(reasoning_trace, llm)
        if result.get("score") is None:
            return 0.5, f"Utility scorer failed: {result.get('error', 'unknown')}"

        iso    = result.get("isolation_index", 0.5)
        detail = (
            f"Isolation index: {round(iso*100)}% of claims unsupported. "
            + result.get("ec_note", "")
        )
        return round(iso, 4), detail


# ── Environment (state management) ──────────────────────────────────────────

class ExecutionEnvironment:
    """
    Tracks agent permissions and in-memory state history.

    IMPORTANT: rollback() restores in-memory state only. It cannot undo
    actual filesystem changes, database writes, or external API calls.
    For production use, wrap destructive operations in transactions or
    use reversible staging before committing.
    """

    def __init__(self):
        self._access: dict[str, bool]  = {}        # agent_id → has_access
        self._history: list[dict]      = []
        self._current: dict            = {}

    def grant_access(self, agent_id: str):
        self._access[agent_id] = True

    def has_access(self, agent_id: str) -> bool:
        return self._access.get(agent_id, True)    # default: allow

    def revoke_access(self, agent_id: str):
        self._access[agent_id] = False
        logger.error(f"Access revoked for [{agent_id}]")

    def snapshot(self):
        self._history.append({
            "ts":      time.time(),
            "state":   self._current.copy(),
            "access":  dict(self._access),
        })

    def rollback(self) -> bool:
        if not self._history:
            logger.warning("No history to roll back to")
            return False
        prev = self._history.pop()
        self._current = prev["state"]
        self._access  = prev["access"]
        logger.warning(f"Rolled back to state at {prev['ts']:.3f} (in-memory only)")
        return True

    def update(self, key: str, value):
        self._current[key] = value


# ── Immune System (orchestrator) ────────────────────────────────────────────

# Thresholds: fraction of max danger/entropy/incoherence above which action is blocked.
# Calibration notes:
#   LOW/semantic_entropy: 0.60 means >60% of max entropy → uncertain → block
#   HIGH/log_det:         0.45 means action cloud is noticeably diffuse → block
#   REASONING/isolation:  0.55 means >55% of claims unsupported → block
# Run cli.py --calibrate to check these against your provider + use case.
DEFAULT_THRESHOLDS: dict[TaskRisk, float] = {
    TaskRisk.LOW:       0.60,
    TaskRisk.HIGH:      0.45,
    TaskRisk.REASONING: 0.55,
}


class EpistemicImmuneSystem:
    """
    Runtime action gate for AI agents.

    Usage:
        from auditor import auto_config
        from immune import EpistemicImmuneSystem, AgentAction, TaskRisk

        cfg    = auto_config()
        immune = EpistemicImmuneSystem(cfg.llm, cfg.embed)

        verdict = immune.evaluate(AgentAction(
            agent_id         = "Claude-Worker-1",
            proposed_command = "rm -rf /usr/local/bin/python",
            task_risk        = TaskRisk.HIGH,
        ))

        if verdict.passed:
            execute_action(...)
    """

    def __init__(
        self,
        llm:        LLMProvider,
        embed:      EmbedProvider,
        thresholds: dict[TaskRisk, float] | None = None,
        on_block:   Callable[[ImmuneVerdict], None] | None = None,
    ):
        self.llm        = llm
        self.embed      = embed
        self.thresholds = thresholds or dict(DEFAULT_THRESHOLDS)
        self.on_block   = on_block          # optional callback when action is blocked
        self.env        = ExecutionEnvironment()

    def evaluate(self, action: AgentAction) -> ImmuneVerdict:
        """
        Route action to appropriate detector. Return ImmuneVerdict.
        Blocks automatically if score exceeds threshold.
        """
        t0        = time.time()
        threshold = self.thresholds[action.task_risk]

        logger.info(
            f"[{action.agent_id}] Evaluating: '{action.proposed_command[:60]}' "
            f"(risk={action.task_risk.value.upper()})"
        )

        self.env.snapshot()

        try:
            if action.task_risk == TaskRisk.LOW:
                score, detail = EpistemicDetectors.semantic_entropy(
                    action.proposed_command, self.llm, self.embed
                )
                detector = "semantic_entropy (Farquhar et al. Nature 2024)"

            elif action.task_risk == TaskRisk.HIGH:
                score, detail = EpistemicDetectors.covariance_log_det(
                    action.proposed_command, self.llm, self.embed
                )
                detector = "covariance_log_det (ChiralCheck T2 proxy for EigenScore)"

            elif action.task_risk == TaskRisk.REASONING:
                trace = (action.proposed_command + " " + action.context).strip()
                score, detail = EpistemicDetectors.effective_complexity_proxy(
                    trace, self.llm
                )
                detector = "effective_complexity_proxy (utility isolation_index)"

            else:
                score, detail, detector = 0.0, "Unknown risk level", "none"

        except Exception as e:
            logger.error(f"Detector raised unhandled exception: {e}")
            self.env.rollback()
            return ImmuneVerdict(
                passed=False, score=1.0, threshold=threshold,
                detector_used="error", agent_id=action.agent_id,
                proposed_command=action.proposed_command, task_risk=action.task_risk,
                detail=f"Detector exception: {e}", elapsed_s=round(time.time()-t0, 2),
            )

        passed  = score <= threshold
        elapsed = round(time.time() - t0, 2)

        if passed:
            logger.info(
                f"[{action.agent_id}] CLEARED  score={score:.3f} ≤ {threshold:.2f} | {detail}"
            )
        else:
            self._trigger_immune_response(action, score, threshold, detail)

        return ImmuneVerdict(
            passed=passed, score=score, threshold=threshold,
            detector_used=detector, agent_id=action.agent_id,
            proposed_command=action.proposed_command, task_risk=action.task_risk,
            detail=detail, elapsed_s=elapsed,
        )

    def _trigger_immune_response(
        self,
        action:    AgentAction,
        score:     float,
        threshold: float,
        detail:    str,
    ):
        logger.error(f">>> IMMUNE RESPONSE <<<")
        logger.error(
            f"[{action.agent_id}] BLOCKED  score={score:.3f} > {threshold:.2f} | {detail}"
        )

        if action.task_risk == TaskRisk.HIGH:
            self.env.revoke_access(action.agent_id)

        self.env.rollback()

        if self.on_block:
            try:
                self.on_block(ImmuneVerdict(
                    passed=False, score=score, threshold=threshold,
                    detector_used="", agent_id=action.agent_id,
                    proposed_command=action.proposed_command, task_risk=action.task_risk,
                    detail=detail,
                ))
            except Exception:
                pass


# ── Vector math helpers (no numpy) ───────────────────────────────────────────

def _cosine(a: list[float], b: list[float]) -> float:
    dot = sum(x*y for x,y in zip(a,b))
    na  = math.sqrt(sum(x*x for x in a))
    nb  = math.sqrt(sum(x*x for x in b))
    return dot/(na*nb) if na>0 and nb>0 else 0.0


def _count_clusters(vecs: list[list[float]], thr: float = 0.82) -> int:
    cs = []
    for v in vecs:
        if not any(_cosine(v,c) >= thr for c in cs): cs.append(v)
    return len(cs)


def _cosine_cluster_entropy(vecs: list[list[float]], thr: float = 0.82) -> float:
    """Shannon entropy over greedy cosine-cluster distribution."""
    centroids: list[list[float]] = []
    counts:    list[int]         = []
    for v in vecs:
        j = next((j for j,c in enumerate(centroids) if _cosine(v,c)>=thr), None)
        if j is not None:
            n = counts[j]
            centroids[j] = [(centroids[j][i]*n+v[i])/(n+1) for i in range(len(v))]
            counts[j] += 1
        else:
            centroids.append(list(v)); counts.append(1)
    total = sum(counts)
    if total == 0: return 0.0
    return -sum((c/total)*math.log(c/total) for c in counts if c>0)


def _clip_features(vecs: list[list[float]], pct: float = 0.90) -> list[list[float]]:
    d   = len(vecs[0])
    ma  = [sum(abs(v[i]) for v in vecs)/len(vecs) for i in range(d)]
    thr = sorted(ma)[min(int(pct*d), d-1)]
    return [[0.0 if ma[i]>thr else x for i,x in enumerate(v)] for v in vecs]


def _log_det_normalised(vecs: list[list[float]]) -> float:
    if len(vecs) < 2: return 0.0
    d  = len(vecs[0])
    mu = [sum(v[i] for v in vecs)/len(vecs) for i in range(d)]
    va = [sum((v[i]-mu[i])**2 for v in vecs)/(len(vecs)-1) for i in range(d)]
    return sum(math.log(v+1e-4) for v in va)/d


# ── Convenience: wrap existing auditor for idea scoring ──────────────────────

def immune_audit_idea(
    text:   str,
    llm:    LLMProvider,
    embed:  EmbedProvider,
) -> dict:
    """
    Convenience wrapper: runs the full 4-axis idea audit (from auditor.py)
    but gates it through the immune system first.

    The REASONING detector checks whether the idea text itself is coherent
    before spending the full audit budget on it.
    """
    from auditor import audit, Config

    # Pre-flight: REASONING check on the idea text
    immune = EpistemicImmuneSystem(llm, embed)
    gate   = immune.evaluate(AgentAction(
        agent_id="idea-auditor",
        proposed_command=text[:500],
        task_risk=TaskRisk.REASONING,
        context="Pre-flight coherence check before full ChiralCheck audit",
    ))

    if not gate.passed:
        return {
            "immune_gate": "BLOCKED",
            "reason": gate.detail,
            "score":  gate.score,
            "threshold": gate.threshold,
            "note": "Idea failed pre-flight coherence check. Full audit skipped.",
        }

    # Full audit
    cfg    = Config(llm, embed, "immune", "immune")
    result = audit(text, cfg, verbose=False)
    result["immune_gate"] = "PASSED"
    result["immune_detail"] = gate.detail
    return result
